# Generated by Django 3.2 on 2024-08-07 05:57

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=videos.models.video_upload_path),
        ),
    ]
